---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myteam-prod
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./myteam/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: myteam
