---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myteam-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./myteam/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: myteam
